{% set name = "python-cpl" %}
{% set version = "0.7.4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '6dfca58676967b752b2cdf636e1d6094f02259fcaaad5ed167f32ff0b69ee76b'

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - astropy

test:
  imports:
    - cpl

about:
  home: https://pypi.python.org/pypi/python-cpl
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: Python interface for the ESO Common Pipeline Library
  description: |
    This module can list, configure and execute CPL-based recipes from Python
    (python2 and python3).  The input, calibration and output data can be
    specified as FITS files or as astropy.io.fits objects in memory. The ESO
    Common Pipeline Library (CPL) comprises a set of ISO-C libraries that
    provide a comprehensive, efficient and robust software toolkit. It forms a
    basis for the creation of automated astronomical data-reduction tasks. One
    of the features provided by the CPL is the ability to create data-
    reduction algorithms that run as plugins (dynamic libraries). These are
    called "recipes" and are one of the main aspects of the CPL data-reduction
    development environment.
  doc_url: http://pythonhosted.org/python-cpl/
  dev_url: https://github.com/olebole/python-cpl

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - olebole
    - hugobuddel
