appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EBJy1HzJDH4EQ9/HzlQphpnamq+kVFtjRygdnXcMvbNqEGSTy9lXLEpReR735nzCrEroxLm1Vbir7mHNpxL0hkm4fpbXpBjZiv174P4hp57LA8+Xda95MSBvRj6tDUZgEg4Y0sD6hq4A9sftWg/SatbVpQ9Q8vYiZisAZsHbYisdYfwssgxfWnzQ4Q5bcOfFisrkDnhHVNKy1c4aDy202WpzkzdP6dc0nygzAp8l+7FBIBpTNWGHK2ZuL+8gcTrkDkw9VvEnPEdRqhwCuGZ+M+hQQzsDtPYg6l9HtDNEXrekq3ubwzbcvFUpbEPFdFmwdMOPJj1KA7Sp4mKZEhsPMj+20r33Lh22xG3fiQ8Bj38T/C7xMfzF2eyYjYPMGGxK5FkTX+JOTKwG58cQZKrkr3edCwm93v+6NcWLvxnsGJ4UAx9ZbGvWijJLTSNM22uWM3KFzJVhL1Smp6GZYL5M2Y/KeVtqljYhskhdpviw4ybp67W82xj1DECUXhVBj9W8ePgKRfiO8D2w9Ym8R0BTzQ7Iqg6YMnEyvNz7Uy2wnunD6FTt5noJrVkB4NC31fQNkOtDvDSyB1awjBvMV7aejSNlDfstFNGCFP0IAx3uEhNM/NZmjZbtkdn0ETzXFNhyScnqEKH3IyRp7WAllD8qre+xtoKaJz4frP/y8oGm/ss=}
